apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
      worker_connections  1024;
    }

    http {
      include /etc/nginx/mime.types;

      server {
          listen 80;

          location /api/ {
            proxy_http_version 1.1;
            proxy_pass  http://api:3000/;
          }

          location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
          }
        }
    }