apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-v2
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        version: v2
    spec:
      containers:
      - name: web
        image: nginx:1.20
        resources:
          limits:
            memory: "50Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            name: nginx-config
          - mountPath: /usr/share/nginx/html/index.html
            subPath: index.html
            name: index
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: index
          configMap:
            name: index-v2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-v2
data:
  index.html: |
    <html>
      <head>
        <title>Istio Gateway Demo</title>
        <style>
          body {
            font-family: Arial, Helvetica, sans-serif;
          }
          nav {
            background-color: aqua;
            padding: 15px;
            font-weight: 400;
          }
          footer {
            position: absolute;
            bottom: 10px;
            right: 10px;
            color: #777;
          }
        </style>
      </head>
      <body>
        <nav>
          <div class="brand">Version Manager</div>
        </nav>
        <footer id="version">v1 copy right 2022</footer>
        <script>
          fetch(`${window.location.origin}/api/`).then(res => res.json()).then(version => document.getElementById('version').innerHTML = version);
        </script>
      </body>
    </html>